#!/bin/bash

BLANK_PAGE=http://raw.github.com/esin/Esin-s-scripts/master/sh/yota/blank.html
CURL_OPTS='--retry 100000 --retry-delay 1 --silent --compressed' # --user-agent Opera/9.80 (X11; Linux i686; U; ru) Presto/2.9.168 Version/11.51'
HEADER_DUMP=`mktemp`

curl $BLANK_PAGE $CURL_OPTS --dump-header $HEADER_DUMP

# Beeline WiFi Free. Mega
if [ `grep -e "HTTP/1.1 302 " -e "Location: http://startwifi.beeline.ru" $HEADER_DUMP | wc -l` -eq "2" ]; then
   echo "Beeline WiFi Free. Mega"
   curl https://startwifi.beeline.ru/status $CURL_OPTS \
   --data "lang=ru&screen=normal&url=http://127.0.0.1&mode=device&submode=tcmega" > /dev/null
fi

# Beeline WiFi Free
if [ `grep -e "HTTP/1.1 302 " -e "Location: http://startwifi.beeline.ru" $HEADER_DUMP | wc -l` -eq "2" ]; then
  echo "Beeline WiFi Free"
  curl https://startwifi.beeline.ru/status $CURL_OPTS \
  --data "lang=ru&screen=pda&url=http://127.0.0.1&redirect=1" > /dev/null
fi

#Yota. Msk

if [ `grep -i -e "HTTP/1.1 302 Found" -e "Location: http://hello.yota.ru/light" $HEADER_DUMP | wc -l` -eq "2" ]; then
  echo "Yota. Msk"
  curl http://hello.yota.ru/php/go.php $CURL_OPTS \
  --data "accept_lte=1&redirurl=http://www.yota.ru/&city=msk&connection_type=sa&service_id=Service_Access_Temp" > /dev/null

  curl http://hello.yota.ru/php/go.php $CURL_OPTS \
  --data "accept_lte=1&redirurl=http://www.yota.ru/&city=msk&connection_type=light&service_id=Sliders_Free_Temp" > /dev/null

  exit 0
fi

exit 0
