#!/bin/bash

BLANK_PAGE=http://raw.github.com/esin/Esin-s-scripts/master/sh/yota/blank.html
IS_302=`curl $BLANK_PAGE --retry 100000 --retry-delay 1 --silent --compressed --dump-header - | grep "HTTP/1.1 302 Found" | wc -l`

CURL_OPTS='-D > /dev/null --retry 100000 --retry-delay 1 --silent --compressed'
if [ $IS_302 -eq "1" ]; then
  curl http://hello.yota.ru/php/go.php $CURL_OPTS \
   --data "accept_lte=1&redirurl=http://www.yota.ru/&city=msk&connection_type=sa&service_id=Service_Access_Temp"

  curl http://hello.yota.ru/php/go.php $CURL_OPTS \
   --data "accept_lte=1&redirurl=http://www.yota.ru/&city=msk&connection_type=light&service_id=Sliders_Free_Temp"

  curl https://startwifi.beeline.ru/status $CURL_OPTS \
   --data "lang=ru&screen=pda&url=http://127.0.0.1&redirect=1"
fi
