#!/bin/bash

recognize()
{
 echo `file -bpr $1`
}

parser()
{
 echo -n $1 
#$(echo -n $1 | cut -d'/' -f2)
}

choose_act()
{
# $1 - filetype
# $2 - full filename
# $3 - pretty filename

 if [ $(echo $1 | grep -e "[zZ]ip" | wc -l) -ge "1" ]; then
  echo "Unziping $3"
  unzip -q $2
 fi

 if [ $(echo $1 | grep -e "RAR" | wc -l) -ge "1" ]; then
  echo "Unraring $3"
  unrar -inul x $2
 fi

 if [ $(echo $1 | grep -e "gzip compressed data" | wc -l) -ge "1" ]; then
  echo "Ungziping..."
  gzip -d $2
 fi

 if [ $(echo $1 | grep -e "bzip2 compressed data" | wc -l) -ge "1" ]; then
  echo "Unbziping..."
  bzip2 -d $2
 fi

 if [ $(echo $1 | grep -e "\(PE32 executable\)\|\(MS-DOS executable\)" | wc -l) -ge "1" ]; then
  echo "Running in wine..."
  wine $2
 fi


#  "x-empty"
#   echo "$3 is empty"
# 
}

q()
{
 res=$(recognize $1)
 filetype=$(parser $res)
 choose_act "$res" "$(readlink -f $1)" "$1"
}
